import type {
  Asset,
  AuditLog,
  Category,
  Department,
  Employee,
  Item,
  Location,
  Role,
  Stock,
  Warehouse,
} from "./types";

// ============ LOCATIONS ============
export const initialLocations: Location[] = [
  {
    id: "loc-1",
    name: "Headquarters",
    code: "HQ",
    address: "123 Main Street, District 1, Ho Chi Minh City",
    created_at: "2024-01-01",
  },
  {
    id: "loc-2",
    name: "Branch Office",
    code: "BR-01",
    address: "456 Nguyen Hue, District 3, Ho Chi Minh City",
    created_at: "2024-01-01",
  },
  {
    id: "loc-3",
    name: "Data Center",
    code: "DC-01",
    address: "789 Le Loi, District 7, Ho Chi Minh City",
    created_at: "2024-01-01",
  },
  {
    id: "loc-4",
    name: "Remote Office",
    code: "RO-01",
    address: "321 Tran Hung Dao, Da Nang",
    created_at: "2024-02-15",
  },
];

// ============ ROLES ============
export const initialRoles: Role[] = [
  {
    id: "role-1",
    name: "Administrator",
    code: "ADMIN",
    description: "Full system access",
    created_at: "2024-01-01",
  },
  {
    id: "role-2",
    name: "IT Manager",
    code: "IT_MGR",
    description: "Manage IT assets and assignments",
    created_at: "2024-01-01",
  },
  {
    id: "role-3",
    name: "Employee",
    code: "EMP",
    description: "View and request assets",
    created_at: "2024-01-01",
  },
  {
    id: "role-4",
    name: "Warehouse Staff",
    code: "WH_STAFF",
    description: "Manage warehouse inventory",
    created_at: "2024-01-01",
  },
  {
    id: "role-5",
    name: "Department Head",
    code: "DEPT_HEAD",
    description: "Approve department requests",
    created_at: "2024-01-01",
  },
];

// ============ DEPARTMENTS ============
export const initialDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Information Technology",
    code: "IT",
    manager_id: "emp-1",
    location_id: "loc-1",
    created_at: "2024-01-01",
  },
  {
    id: "dept-2",
    name: "Human Resources",
    code: "HR",
    manager_id: "emp-4",
    location_id: "loc-1",
    created_at: "2024-01-01",
  },
  {
    id: "dept-3",
    name: "Finance",
    code: "FIN",
    manager_id: "emp-5",
    location_id: "loc-1",
    created_at: "2024-01-01",
  },
  {
    id: "dept-4",
    name: "Marketing",
    code: "MKT",
    manager_id: "emp-6",
    location_id: "loc-2",
    created_at: "2024-01-01",
  },
  {
    id: "dept-5",
    name: "Operations",
    code: "OPS",
    manager_id: "emp-7",
    location_id: "loc-2",
    created_at: "2024-01-15",
  },
];

// ============ EMPLOYEES ============
export const initialEmployees: Employee[] = [
  {
    id: "emp-1",
    employee_code: "EMP001",
    full_name: "Nguyen Van A",
    email: "nva@company.com",
    phone: "0901234567",
    department_id: "dept-1",
    position: "IT Manager",
    manager_id: null,
    status: "active",
    avatar_url: null,
    joined_date: "2022-01-15",
    created_at: "2022-01-15",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-2",
  },
  {
    id: "emp-2",
    employee_code: "EMP002",
    full_name: "Tran Thi B",
    email: "ttb@company.com",
    phone: "0901234568",
    department_id: "dept-1",
    position: "System Administrator",
    manager_id: "emp-1",
    status: "active",
    avatar_url: null,
    joined_date: "2022-03-20",
    created_at: "2022-03-20",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-1",
  },
  {
    id: "emp-3",
    employee_code: "EMP003",
    full_name: "Le Van C",
    email: "lvc@company.com",
    phone: "0901234569",
    department_id: "dept-1",
    position: "Network Engineer",
    manager_id: "emp-1",
    status: "active",
    avatar_url: null,
    joined_date: "2022-06-01",
    created_at: "2022-06-01",
    updated_at: "2024-01-01",
    location_id: "loc-3",
    role_id: "role-3",
  },
  {
    id: "emp-4",
    employee_code: "EMP004",
    full_name: "Pham Thi D",
    email: "ptd@company.com",
    phone: "0901234570",
    department_id: "dept-2",
    position: "HR Manager",
    manager_id: null,
    status: "active",
    avatar_url: null,
    joined_date: "2021-08-10",
    created_at: "2021-08-10",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-5",
  },
  {
    id: "emp-5",
    employee_code: "EMP005",
    full_name: "Hoang Van E",
    email: "hve@company.com",
    phone: "0901234571",
    department_id: "dept-3",
    position: "Finance Director",
    manager_id: null,
    status: "active",
    avatar_url: null,
    joined_date: "2020-05-15",
    created_at: "2020-05-15",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-5",
  },
  {
    id: "emp-6",
    employee_code: "EMP006",
    full_name: "Vo Thi F",
    email: "vtf@company.com",
    phone: "0901234572",
    department_id: "dept-4",
    position: "Marketing Manager",
    manager_id: null,
    status: "active",
    avatar_url: null,
    joined_date: "2021-11-20",
    created_at: "2021-11-20",
    updated_at: "2024-01-01",
    location_id: "loc-2",
    role_id: "role-5",
  },
  {
    id: "emp-7",
    employee_code: "EMP007",
    full_name: "Dang Van G",
    email: "dvg@company.com",
    phone: "0901234573",
    department_id: "dept-5",
    position: "Operations Manager",
    manager_id: null,
    status: "active",
    avatar_url: null,
    joined_date: "2021-09-01",
    created_at: "2021-09-01",
    updated_at: "2024-01-01",
    location_id: "loc-2",
    role_id: "role-5",
  },
  {
    id: "emp-8",
    employee_code: "EMP008",
    full_name: "Bui Thi H",
    email: "bth@company.com",
    phone: "0901234574",
    department_id: "dept-1",
    position: "Warehouse Staff",
    manager_id: "emp-1",
    status: "active",
    avatar_url: null,
    joined_date: "2023-02-01",
    created_at: "2023-02-01",
    updated_at: "2024-01-01",
    location_id: "loc-3",
    role_id: "role-4",
  },
  {
    id: "emp-9",
    employee_code: "EMP009",
    full_name: "Ngo Van I",
    email: "nvi@company.com",
    phone: "0901234575",
    department_id: "dept-2",
    position: "HR Specialist",
    manager_id: "emp-4",
    status: "on_leave",
    avatar_url: null,
    joined_date: "2023-04-15",
    created_at: "2023-04-15",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-3",
  },
  {
    id: "emp-10",
    employee_code: "EMP010",
    full_name: "Truong Thi K",
    email: "ttk@company.com",
    phone: "0901234576",
    department_id: "dept-3",
    position: "Accountant",
    manager_id: "emp-5",
    status: "active",
    avatar_url: null,
    joined_date: "2023-07-01",
    created_at: "2023-07-01",
    updated_at: "2024-01-01",
    location_id: "loc-1",
    role_id: "role-3",
  },
];

// ============ CATEGORIES ============
export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Hardware",
    code: "HW",
    parent_id: null,
    description: "Physical computing equipment",
    icon: "Monitor",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-2",
    name: "Software",
    code: "SW",
    parent_id: null,
    description: "Software licenses and subscriptions",
    icon: "Package",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-3",
    name: "Network Equipment",
    code: "NET",
    parent_id: null,
    description: "Network infrastructure devices",
    icon: "Wifi",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-4",
    name: "Peripherals",
    code: "PER",
    parent_id: null,
    description: "Computer peripherals and accessories",
    icon: "Mouse",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-5",
    name: "Laptops",
    code: "HW-LP",
    parent_id: "cat-1",
    description: "Portable computers",
    icon: "Laptop",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-6",
    name: "Desktops",
    code: "HW-DT",
    parent_id: "cat-1",
    description: "Desktop computers",
    icon: "Monitor",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-7",
    name: "Servers",
    code: "HW-SV",
    parent_id: "cat-1",
    description: "Server hardware",
    icon: "Server",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-8",
    name: "Monitors",
    code: "PER-MN",
    parent_id: "cat-4",
    description: "Display monitors",
    icon: "Monitor",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-9",
    name: "Printers",
    code: "PER-PR",
    parent_id: "cat-4",
    description: "Printers and scanners",
    icon: "Printer",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "cat-10",
    name: "Routers",
    code: "NET-RT",
    parent_id: "cat-3",
    description: "Network routers",
    icon: "Router",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
];

// ============ WAREHOUSES ============
export const initialWarehouses: Warehouse[] = [
  {
    id: "wh-1",
    name: "Main Warehouse",
    code: "WH-MAIN",
    address: "123 Main Street, District 1, HCM",
    manager_id: "emp-8",
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "wh-2",
    name: "Data Center Storage",
    code: "WH-DC",
    address: "789 Le Loi, District 7, HCM",
    manager_id: "emp-3",
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "wh-3",
    name: "Branch Storage",
    code: "WH-BR",
    address: "456 Nguyen Hue, District 3, HCM",
    manager_id: "emp-7",
    created_at: "2024-02-01",
    updated_at: "2024-02-01",
  },
];

// ============ ITEMS ============
export const initialItems: Item[] = [
  {
    id: "asset-1",
    item_code: "MBP-2024-001",
    item_name: 'MacBook Pro 16"',
    category_id: "cat-5",
    brand: "Apple",
    model: 'MacBook Pro 16" M3 Max',
    specification: "64GB RAM, 1TB SSD, M3 Max chip",
    // purchase_date: "2024-01-15",
    // purchase_cost: 75000000,
    supplier_url: "https://apple.com",
    status: "inactive",
    image_url: null,
    note: "Development team laptop",
    created_by: "emp-2",
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
    deleted_at: null,
  },
  {
    id: "asset-2",
    item_code: "DM27-2024-042",
    item_name: 'Dell UltraSharp 27"',
    category_id: "cat-8",
    brand: "Dell",
    model: "U2723QE",
    specification: "4K IPS, USB-C Hub, 60Hz",
    // purchase_date: "2024-02-20",
    // purchase_cost: 15000000,
    supplier_url: "https://dell.com",
    status: "active",
    image_url: null,
    note: "4K display for design team",
    created_by: "emp-2",
    created_at: "2024-02-20",
    updated_at: "2024-02-20",
    deleted_at: null,
  },
  {
    id: "asset-3",
    item_code: "CSW-48-2023-015",
    item_name: "Cisco Catalyst Switch",
    category_id: "cat-3",
    brand: "Cisco",
    model: "C9300-48P",
    specification: "48 Port PoE+, 10G Uplink",
    // purchase_date: "2023-08-10",
    // purchase_cost: 120000000,
    supplier_url: "https://cisco.com",
    status: "active",
    image_url: null,
    note: "Main network switch",
    created_by: "emp-1",
    created_at: "2023-08-10",
    updated_at: "2023-08-10",
    deleted_at: null,
  },
  {
    id: "asset-4",
    item_code: "ACC-2024-ENT-001",
    item_name: "Adobe Creative Cloud",
    category_id: "cat-2",
    brand: "Adobe",
    model: "Creative Cloud All Apps",
    specification: "25-seat enterprise license",
    // purchase_date: "2024-03-01",
    // purchase_cost: 180000000,
    supplier_url: "https://adobe.com",
    status: "active",
    image_url: null,
    note: "Annual subscription",
    created_by: "emp-1",
    created_at: "2024-03-01",
    updated_at: "2024-03-01",
    deleted_at: null,
  },
  {
    id: "asset-5",
    item_code: "HPLJ-2022-088",
    item_name: "HP LaserJet Pro",
    category_id: "cat-9",
    brand: "HP",
    model: "M428fdw",
    specification: "Multifunction laser printer",
    // purchase_date: "2022-06-15",
    // purchase_cost: 12000000,
    supplier_url: "https://hp.com",
    status: "inactive",
    image_url: null,
    note: "Scheduled for maintenance",
    created_by: "emp-2",
    created_at: "2022-06-15",
    updated_at: "2024-05-01",
    deleted_at: null,
  },
  {
    id: "asset-6",
    item_code: "TPX1-2020-112",
    item_name: "ThinkPad X1 Carbon",
    category_id: "cat-5",
    brand: "Lenovo",
    model: "X1 Carbon Gen 8",
    specification: "i7-10510U, 16GB, 512GB",
    // purchase_date: "2020-03-22",
    // purchase_cost: 35000000,
    supplier_url: "https://lenovo.com",
    status: "inactive",
    image_url: null,
    note: "End of life - to be disposed",
    created_by: "emp-1",
    created_at: "2020-03-22",
    updated_at: "2024-01-01",
    deleted_at: null,
  },
  {
    id: "asset-7",
    item_code: "M365-2024-BUS-001",
    item_name: "Microsoft 365 Business",
    category_id: "cat-2",
    brand: "Microsoft",
    model: "Business Premium",
    specification: "100 user license, annual",
    // purchase_date: "2024-01-01",
    // purchase_cost: 250000000,
    supplier_url: "https://microsoft.com",
    status: "active",
    image_url: null,
    note: "100 user license",
    created_by: "emp-1",
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    deleted_at: null,
  },
  {
    id: "asset-8",
    item_code: "UAP-2023-007",
    item_name: "Ubiquiti UniFi AP",
    category_id: "cat-3",
    brand: "Ubiquiti",
    model: "U6-Pro",
    specification: "WiFi 6, 4x4 MIMO, PoE",
    // purchase_date: "2023-11-05",
    // purchase_cost: 5000000,
    supplier_url: "https://ui.com",
    status: "inactive",
    image_url: null,
    note: "WiFi 6 access point",
    created_by: "emp-3",
    created_at: "2023-11-05",
    updated_at: "2023-11-05",
    deleted_at: null,
  },
  {
    id: "asset-9",
    item_code: "SRV-2023-001",
    item_name: "Dell PowerEdge R750",
    category_id: "cat-7",
    brand: "Dell",
    model: "PowerEdge R750",
    specification: "Dual Xeon, 256GB RAM, 8x SSD",
    // purchase_date: "2023-06-01",
    // purchase_cost: 350000000,
    supplier_url: "https://dell.com",
    status: "active",
    image_url: null,
    note: "Production server",
    created_by: "emp-1",
    created_at: "2023-06-01",
    updated_at: "2023-06-01",
    deleted_at: null,
  },
  {
    id: "asset-10",
    item_code: "MBP-2024-002",
    item_name: 'MacBook Pro 14"',
    category_id: "cat-5",
    brand: "Apple",
    model: 'MacBook Pro 14" M3 Pro',
    specification: "36GB RAM, 512GB SSD",
    // purchase_date: "2024-02-01",
    // purchase_cost: 55000000,
    supplier_url: "https://apple.com",
    status: "inactive",
    image_url: null,
    note: "New stock",
    created_by: "emp-2",
    created_at: "2024-02-01",
    updated_at: "2024-02-01",
    deleted_at: null,
  },
];

// ============ STOCKS ============
export const initialStocks: Stock[] = [
  {
    id: "stock-1",
    item_id: "asset-1",
    warehouse_id: "wh-1",
    quantity: 5,
    available_quantity: 2,
    reserved_quantity: 1,
    purchase_date: "2023-06-01",
    purchase_cost: 350000000,
    serials: [
      {
        name: "LTP-01",
      },
      {
        name: "LTP-02",
      },
      { name: "LTP-03", status: "IN_USE" },
    ],
    created_at: "2024-01-15",
    updated_at: "2024-05-01",
  },
  {
    id: "stock-2",
    item_id: "asset-2",
    warehouse_id: "wh-1",
    quantity: 0,
    available_quantity: 0,
    reserved_quantity: 0,
    serials: [
      { name: "MON-01", status: "IN_USE" },
      { name: "MON-02" },
      { name: "MON-03" },
    ],
    purchase_date: "2024-02-01",
    purchase_cost: 75000000,
    created_at: "2024-02-20",
    updated_at: "2024-05-01",
  },
  {
    id: "stock-3",
    item_id: "asset-3",
    warehouse_id: "wh-2",
    quantity: 3,
    available_quantity: 1,
    reserved_quantity: 0,
    purchase_date: "2023-11-05",
    purchase_cost: 5000000,
    serials: [],
    created_at: "2023-08-10",
    updated_at: "2024-03-01",
  },

  {
    id: "stock-4",
    item_id: "asset-10",
    warehouse_id: "wh-1",
    quantity: 8,
    available_quantity: 8,
    reserved_quantity: 0,
    purchase_date: "2024-01-01",
    purchase_cost: 250000000,
    serials: [
      {
        name: "LTP-04",
        status: "IN_USE",
      },
    ],
    created_at: "2024-02-01",
    updated_at: "2024-02-01",
  },
];

// ============ ASSETS ============
export const initialAssets: Asset[] = [
  {
    id: "assign-1",
    stock_id: "stock-1",
    assign_type: "",
    assigned_to: "",
    assigned_date: "2024-01-20",
    expected_return_date: null,
    returned_date: null,
    assignment_status: "",
    asset_status: "AVAILABLE",
    condition_before: "New",
    condition_after: null,
    note: "Primary work device",
    signature_url: null,
    created_at: "2024-01-20",
    updated_at: "2024-01-20",
    created_by: "emp-1",
    quantity: 1,
    serial_number: "MBP001",
    priority: "high",
    asset_code: "LTP-01",
    approved_by: "emp-1",
  },
  {
    id: "assign-2",
    stock_id: "stock-1",
    assign_type: "",
    assigned_to: "",
    assigned_date: "2024-01-25",
    expected_return_date: null,
    returned_date: null,
    assignment_status: "",
    asset_status: "AVAILABLE",
    condition_before: "New",
    condition_after: null,
    note: "Network engineer laptop",
    signature_url: null,
    created_at: "2024-01-25",
    updated_at: "2024-01-25",
    created_by: "emp-1",
    quantity: 1,
    serial_number: "MBP002",
    priority: "high",
    asset_code: "LTP-02",
    approved_by: "emp-1",
  },
  {
    id: "assign-3",
    stock_id: "stock-2",
    assign_type: "EMPLOYEE",
    assigned_to: "emp-6",
    assigned_date: "2024-03-01",
    expected_return_date: null,
    returned_date: null,
    assignment_status: "assigned",
    asset_status: "IN_USE",
    condition_before: "New",
    condition_after: null,
    note: "Design team monitor",
    signature_url: null,
    created_at: "2024-03-01",
    updated_at: "2024-03-01",
    created_by: "emp-2",
    quantity: 2,
    serial_number: "",
    priority: "medium",
    asset_code: "MON-01",
    approved_by: "emp-1",
  },
  {
    id: "assign-4",
    stock_id: "stock-4",
    assign_type: "REQUEST_ASSET",
    assigned_to: "emp-7",
    assigned_date: "2024-02-15",
    expected_return_date: "2024-08-15",
    returned_date: null,
    assignment_status: "assigned",
    asset_status: "IN_USE",
    condition_before: "Good",
    condition_after: null,
    note: "Branch office WiFi deployment",
    signature_url: null,
    created_at: "2024-02-15",
    updated_at: "2024-02-15",
    created_by: "emp-3",
    quantity: 3,
    serial_number: "",
    priority: "medium",
    asset_code: "LTP-04",
    approved_by: "emp-1",
  },
  {
    id: "assign-5",
    stock_id: "stock-1",
    assign_type: "CHANGE_WAREHOUSE",
    assigned_to: "wh-1",
    assigned_date: "2024-04-01",
    expected_return_date: "2024-04-30",
    returned_date: "2024-04-28",
    assignment_status: "assigned",
    asset_status: "IN_USE",
    condition_before: "Good",
    condition_after: "Good",
    note: "Temporary assignment during training",
    signature_url: null,
    created_at: "2024-04-01",
    updated_at: "2024-04-28",
    created_by: "emp-1",
    quantity: 1,
    serial_number: "MBP003",
    priority: "low",
    asset_code: "LTP-03",
    approved_by: "emp-1",
  },
  {
    id: "assign-6",
    stock_id: "stock-2",
    assign_type: "EMPLOYEE",
    assigned_to: "emp-10",
    assigned_date: "2024-05-01",
    expected_return_date: null,
    returned_date: null,
    assignment_status: "pending",
    asset_status: "AVAILABLE",
    condition_before: "New",
    condition_after: null,
    note: "Finance department monitor",
    signature_url: null,
    created_at: "2024-05-01",
    updated_at: "2024-05-01",
    created_by: "emp-2",
    quantity: 1,
    serial_number: "",
    priority: "low",
    asset_code: "MON-02",
    approved_by: null,
  },
  {
    id: "assign-7",
    stock_id: "stock-2",
    assign_type: "DEVICE_RECALL",
    assigned_to: "emp-10",
    assigned_date: "2024-05-01",
    expected_return_date: "2024-05-03",
    returned_date: "2024-05-02",
    assignment_status: "pending",
    asset_status: "AVAILABLE",
    condition_before: "New",
    condition_after: "No",
    note: "Finance department monitor",
    signature_url: null,
    created_at: "2024-05-01",
    updated_at: "2024-05-01",
    created_by: "emp-2",
    quantity: 1,
    serial_number: "",
    priority: "low",
    asset_code: "MON-03",
    approved_by: null,
  },
];

// ============ AUDIT LOGS ============
export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    module: "assets",
    entity_type: "asset",
    entity_id: "asset-1",
    old_value: null,
    new_value: { asset_name: 'MacBook Pro 16"', status: "in_stock" },
    performed_by: "emp-2",
    metadata: { action: "create" },
    created_at: "2024-01-15T09:00:00Z",
  },
  {
    id: "log-2",
    module: "assignments",
    entity_type: "assignment",
    entity_id: "assign-1",
    old_value: null,
    new_value: { status: "assigned", assigned_to: "emp-2" },
    performed_by: "emp-1",
    metadata: { action: "create" },
    created_at: "2024-01-20T10:30:00Z",
  },
  {
    id: "log-3",
    module: "assets",
    entity_type: "asset",
    entity_id: "asset-1",
    old_value: { status: "in_stock" },
    new_value: { status: "deployed" },
    performed_by: "emp-1",
    metadata: { action: "update" },
    created_at: "2024-01-20T10:31:00Z",
  },
  {
    id: "log-4",
    module: "employees",
    entity_type: "employee",
    entity_id: "emp-8",
    old_value: null,
    new_value: { full_name: "Bui Thi H", position: "Warehouse Staff" },
    performed_by: "emp-4",
    metadata: { action: "create" },
    created_at: "2023-02-01T08:00:00Z",
  },
  {
    id: "log-5",
    module: "warehouses",
    entity_type: "warehouse",
    entity_id: "wh-3",
    old_value: null,
    new_value: { name: "Branch Storage", code: "WH-BR" },
    performed_by: "emp-1",
    metadata: { action: "create" },
    created_at: "2024-02-01T14:00:00Z",
  },
  {
    id: "log-6",
    module: "assets",
    entity_type: "asset",
    entity_id: "asset-5",
    old_value: { status: "active" },
    new_value: { status: "maintenance" },
    performed_by: "emp-2",
    metadata: { action: "update", reason: "Scheduled maintenance" },
    created_at: "2024-05-01T11:00:00Z",
  },
  {
    id: "log-7",
    module: "assignments",
    entity_type: "assignment",
    entity_id: "assign-5",
    old_value: { status: "assigned" },
    new_value: { status: "returned", returned_date: "2024-04-28" },
    performed_by: "emp-9",
    metadata: { action: "update" },
    created_at: "2024-04-28T16:00:00Z",
  },
  {
    id: "log-8",
    module: "employees",
    entity_type: "employee",
    entity_id: "emp-9",
    old_value: { status: "active" },
    new_value: { status: "on_leave" },
    performed_by: "emp-4",
    metadata: { action: "update", reason: "Medical leave" },
    created_at: "2024-05-15T09:00:00Z",
  },
];
